//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Richie
{
    public partial class @PlayerInput : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""defence"",
            ""id"": ""86aa8eb7-483d-4648-b518-04e3950d57c3"",
            ""actions"": [
                {
                    ""name"": ""left"",
                    ""type"": ""Button"",
                    ""id"": ""a744634f-2b3b-4d63-ab29-0885261a0c97"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""right"",
                    ""type"": ""Button"",
                    ""id"": ""6b20d319-48f3-419f-bbf6-928c28f88b8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""ed612622-e838-4e71-88c4-50c6afc37ec5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""scroll"",
                    ""type"": ""Value"",
                    ""id"": ""e8460cb4-1e30-4fc3-9d00-20e0d6e48d05"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""mouse"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5ee1f947-198f-4f81-b7e6-ee8f7120765b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""center"",
                    ""type"": ""Button"",
                    ""id"": ""8e7b8eff-2ec7-4984-95f6-b95509e4f54d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8379890d-783c-4d6b-9c11-04fdf4cd7c9d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fa0dd65-8546-4ddf-8651-4e5d3772e5e8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""22544ae1-480c-4c7f-9504-948d4c494c79"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8121d8f1-6781-49df-b6db-b014879f88f9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""abca4c51-2acf-4668-afbc-c76f552c69af"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d8445efe-e94e-4692-a366-54a7c692bc96"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5993f27f-4fb7-4614-ae9d-e03cf0d6fc73"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""1d853dc2-cb22-4b73-a44a-3f6604f7279a"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d21dd3b-4936-40d1-871d-c1f629abfa81"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cc813a5-4ee3-4ab7-b855-be5a512a0140"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""center"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // defence
            m_defence = asset.FindActionMap("defence", throwIfNotFound: true);
            m_defence_left = m_defence.FindAction("left", throwIfNotFound: true);
            m_defence_right = m_defence.FindAction("right", throwIfNotFound: true);
            m_defence_move = m_defence.FindAction("move", throwIfNotFound: true);
            m_defence_scroll = m_defence.FindAction("scroll", throwIfNotFound: true);
            m_defence_mouse = m_defence.FindAction("mouse", throwIfNotFound: true);
            m_defence_center = m_defence.FindAction("center", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // defence
        private readonly InputActionMap m_defence;
        private IDefenceActions m_DefenceActionsCallbackInterface;
        private readonly InputAction m_defence_left;
        private readonly InputAction m_defence_right;
        private readonly InputAction m_defence_move;
        private readonly InputAction m_defence_scroll;
        private readonly InputAction m_defence_mouse;
        private readonly InputAction m_defence_center;
        public struct DefenceActions
        {
            private @PlayerInput m_Wrapper;
            public DefenceActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @left => m_Wrapper.m_defence_left;
            public InputAction @right => m_Wrapper.m_defence_right;
            public InputAction @move => m_Wrapper.m_defence_move;
            public InputAction @scroll => m_Wrapper.m_defence_scroll;
            public InputAction @mouse => m_Wrapper.m_defence_mouse;
            public InputAction @center => m_Wrapper.m_defence_center;
            public InputActionMap Get() { return m_Wrapper.m_defence; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(DefenceActions set) { return set.Get(); }
            public void SetCallbacks(IDefenceActions instance)
            {
                if (m_Wrapper.m_DefenceActionsCallbackInterface != null)
                {
                    @left.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnLeft;
                    @left.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnLeft;
                    @left.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnLeft;
                    @right.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnRight;
                    @right.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnRight;
                    @right.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnRight;
                    @move.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMove;
                    @move.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMove;
                    @move.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMove;
                    @scroll.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnScroll;
                    @scroll.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnScroll;
                    @scroll.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnScroll;
                    @mouse.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMouse;
                    @mouse.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMouse;
                    @mouse.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnMouse;
                    @center.started -= m_Wrapper.m_DefenceActionsCallbackInterface.OnCenter;
                    @center.performed -= m_Wrapper.m_DefenceActionsCallbackInterface.OnCenter;
                    @center.canceled -= m_Wrapper.m_DefenceActionsCallbackInterface.OnCenter;
                }
                m_Wrapper.m_DefenceActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @left.started += instance.OnLeft;
                    @left.performed += instance.OnLeft;
                    @left.canceled += instance.OnLeft;
                    @right.started += instance.OnRight;
                    @right.performed += instance.OnRight;
                    @right.canceled += instance.OnRight;
                    @move.started += instance.OnMove;
                    @move.performed += instance.OnMove;
                    @move.canceled += instance.OnMove;
                    @scroll.started += instance.OnScroll;
                    @scroll.performed += instance.OnScroll;
                    @scroll.canceled += instance.OnScroll;
                    @mouse.started += instance.OnMouse;
                    @mouse.performed += instance.OnMouse;
                    @mouse.canceled += instance.OnMouse;
                    @center.started += instance.OnCenter;
                    @center.performed += instance.OnCenter;
                    @center.canceled += instance.OnCenter;
                }
            }
        }
        public DefenceActions @defence => new DefenceActions(this);
        public interface IDefenceActions
        {
            void OnLeft(InputAction.CallbackContext context);
            void OnRight(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnScroll(InputAction.CallbackContext context);
            void OnMouse(InputAction.CallbackContext context);
            void OnCenter(InputAction.CallbackContext context);
        }
    }
}
